services:
  _defaults:
    public: true

  marduk.module.mk_responsiveslider.repository.slides:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Repository\MkResponsiveSlideRepository'
    public: true
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - Marduk\Module\Mk_ResponsiveSlider\Entity\MkResponsiveSlide

  marduk.module.mk_responsiveslider.form.slides.data_provider:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Form\SlideDataProvider'
    arguments:
      - '@marduk.module.mk_responsiveslider.repository.slides'
      - '@marduk.module.mk_responsiveslider.form.slides.uploader'

  marduk.module.mk_responsiveslider.form.slides.type:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Form\SlideFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
    arguments:
      - '@marduk.module.mk_responsiveslider.form.slides.data_provider'

  marduk.module.mk_responsiveslider.form.slides.uploader:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Uploader\MkResponsiveSlideUploader'

  marduk.module.mk_responsiveslider.form.slides.form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'marduk.module.mk_responsiveslider.form.slides.type'
      - '@marduk.module.mk_responsiveslider.form.slides.data_provider'

  marduk.module.mk_responsiveslider.form.slides.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@marduk.module.mk_responsiveslider.form.slides.data_provider'
      - 'Marduk\Module\Mk_ResponsiveSlider\Form\SlideFormType'
      - 'SlideEdit'
      - 'index'
  
  marduk.module.mk_responsiveslider.controller.slides:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Controller\SlideController'
    arguments:
      - '@marduk.module.mk_responsiveslider.repository.slides'
      - '@marduk.module.mk_responsiveslider.form.slides.form_handler'
      - '@marduk.module.mk_responsiveslider.form.slides.data_provider'
      - '@marduk.module.mk_responsiveslider.presentation.slide'
  
  marduk.module.mk_responsiveslider.presentation.slide:
    class: 'Marduk\Module\Mk_ResponsiveSlider\Presentation\SlideView'
    public: true
    arguments:
      - '@marduk.module.mk_responsiveslider.repository.slides'

